# Generated by Django 4.2 on 2023-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
