# Generated by Django 4.2 on 2023-05-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "studentManagementApp",
            "0003_courses_sessionyear_alter_user_role_teachers_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjects",
            old_name="staff",
            new_name="teacher",
        ),
    ]
