# Generated by Django 4.2 on 2023-05-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0006_studentleave_staffleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Reject", "Reject"),
                    ("Approve", "Approve"),
                    ("Requested", "Requested"),
                ],
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffleave",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studentManagementApp.teachers",
            ),
        ),
    ]
