# Generated by Django 4.2 on 2023-05-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0008_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="studentManagementApp.courses",
            ),
        ),
    ]
