# Generated by Django 4.2 on 2023-05-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0009_alter_students_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentleave",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="studentManagementApp.students",
            ),
        ),
    ]
