# Generated by Django 4.2 on 2023-05-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0010_alter_studentleave_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentleave",
            old_name="user",
            new_name="student",
        ),
    ]
