# Generated by Django 4.2 on 2023-05-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0011_rename_user_studentleave_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffleave",
            old_name="user",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="studentleave",
            old_name="student",
            new_name="user",
        ),
    ]
