# Generated by Django 4.2 on 2023-05-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0012_rename_user_staffleave_teacher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentleave",
            old_name="user",
            new_name="student",
        ),
    ]
