# Generated by Django 4.2 on 2023-05-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0013_rename_user_studentleave_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentManagementApp.attendance",
                    ),
                ),
            ],
        ),
    ]
