# Generated by Django 4.2 on 2023-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentManagementApp", "0014_attendancenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profileImages"),
        ),
    ]
